services:
  analytics-api:
    container_name: analytics-api
    build: .
    ports:
      - "8083:8080"
    volumes:
      - ./service-account.json:/app/service-account.json:ro
    env_file:
      - .env
    restart: unless-stopped
